version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: taskflow-postgres

    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123

    ports:
      - "5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    container_name: taskflow-app

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskflow
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root123

volumes:
  postgres_data: