spring.application.name=taskflow-backend

spring.profiles.active=dev

server.port=8080

app.version=1.0.0

# ==========================
# Database Configuration
# ==========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/taskflow}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}


# ==========================
# JPA Configuration
# ==========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Flyway Configuration
# ==========================
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=false

# ==========================
# Actuator Configuration
# ==========================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

# ==========================
# Application Information
# ==========================
info.app.name=TaskFlow Backend
info.app.version=${app.version}
info.app.description=TaskFlow Internship Project